apiVersion: v1
kind: ConfigMap

data: 
  WELCOME_MESSAGE: "Welcome to the SEIP lab assignment. This student is having a breakdown over it hehe"
  NODE_ENV: "production"

metadata:
  name: echo-api-config